# Generated by Django 5.2.3 on 2025-07-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0002_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='surbub',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
