# Generated by Django 5.2.3 on 2025-07-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0003_property_surbub'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
