# Generated by Django 5.2.3 on 2025-07-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0004_car_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Nissan', 'Nissan'), ('Honda', 'Honda'), ('Isuzu', 'Isuzu'), ('Mazda', 'Mazda')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('it', 'IT & Software'), ('construction', 'Construction'), ('education', 'Education')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('Houses for Sale', 'Houses for Sale'), ('Land for sale', 'Land for Sale'), ('Houses To Rent', 'Houses to Rent')], max_length=20),
        ),
    ]
