# Generated by Django 5.2.3 on 2025-07-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0006_advertcategory_alter_job_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
