# Generated by Django 5.2.3 on 2025-07-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0011_property_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
