# Generated by Django 5.2.3 on 2025-08-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0013_amenity_property_amenities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
    ]
